/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Cliente;
import Model.Pedido;
import Model.Restaurante;
import java.util.ArrayList;
import Controller.FuncionesClienteDelivery;
import Model.Producto;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Franco Coward
 */
public class ValidarPedido extends javax.swing.JFrame {

    FuncionesClienteDelivery controlador = new FuncionesClienteDelivery();

    /**
     * Creates new form ValidarPedido
     */
    public ValidarPedido() {
        initComponents();
    }

    private ArrayList<Producto> parsearProductos(String textoProductos) {
        ArrayList<Producto> productos = new ArrayList<>();
        String[] lineas = textoProductos.split("\n");
        for (String linea : lineas) {
            String[] partes = linea.split(" - "); // Asumiendo que el formato es "Nombre - Precio"
            if (partes.length == 2) {
                String nombre = partes[0];
                int precio = Integer.parseInt(partes[1].replaceAll("[^\\d]", "")); // Elimina cualquier carácter no numérico
                productos.add(new Producto(nombre, precio));
            }
        }
        return productos;
    }
    
        private Cliente cliente;
    private ArrayList<Producto> productos;
    private String restaurante;

    public ValidarPedido(Cliente cliente, ArrayList<Producto> productos, String restaurante) {
        this.cliente = cliente;
        this.productos = productos;
        this.restaurante = restaurante;
        initComponents();
        llenarDatos();
    }

    private void llenarDatos() {
        txtNombreConfirmar.setText(cliente.getNombre());
        txtTelefonoConfirmar.setText(String.valueOf(cliente.getNumeroTelefono()));
        txtDireccionConfirmar.setText(cliente.getDireccion());
        txtRestauranteConfirmar.setText(restaurante);
        
        StringBuilder detallesPedido = new StringBuilder();
        for (Producto producto : productos) {
            detallesPedido.append(producto.getNombre()).append(" - ").append(producto.getPrecio()).append("\n");
        }
        txtPedidoConfirmar.setText(detallesPedido.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPortada = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNombreConfirmar = new javax.swing.JTextField();
        lblNombreConfirmar = new javax.swing.JLabel();
        lblTelefonoConfirmar = new javax.swing.JLabel();
        lblDireccionConfirmar = new javax.swing.JLabel();
        txtTelefonoConfirmar = new javax.swing.JTextField();
        txtDireccionConfirmar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPedidoConfirmar = new javax.swing.JTextField();
        btnConfirmarPedido = new javax.swing.JButton();
        lblRestauranteConfirmar = new javax.swing.JLabel();
        txtRestauranteConfirmar = new javax.swing.JTextField();
        btnEditarConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPortada.setText("Validar Datos Ingresados");

        jLabel1.setText("Datos del Cliente");

        txtNombreConfirmar.setEditable(false);
        txtNombreConfirmar.setEnabled(false);
        txtNombreConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreConfirmarActionPerformed(evt);
            }
        });

        lblNombreConfirmar.setText("Nombre:");

        lblTelefonoConfirmar.setText("Telefono:");

        lblDireccionConfirmar.setText("Direccion de Envio:");

        txtTelefonoConfirmar.setEnabled(false);
        txtTelefonoConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoConfirmarActionPerformed(evt);
            }
        });

        txtDireccionConfirmar.setEnabled(false);
        txtDireccionConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionConfirmarActionPerformed(evt);
            }
        });

        jLabel2.setText("Pedido:");

        txtPedidoConfirmar.setEnabled(false);
        txtPedidoConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPedidoConfirmarActionPerformed(evt);
            }
        });

        btnConfirmarPedido.setText("Confirmar Pedido");
        btnConfirmarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarPedidoActionPerformed(evt);
            }
        });

        lblRestauranteConfirmar.setText("Restaurante");

        txtRestauranteConfirmar.setEnabled(false);
        txtRestauranteConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRestauranteConfirmarActionPerformed(evt);
            }
        });

        btnEditarConfirmar.setText("Editar");
        btnEditarConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTelefonoConfirmar)
                                    .addComponent(lblNombreConfirmar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombreConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                    .addComponent(txtTelefonoConfirmar)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblRestauranteConfirmar)
                                            .addComponent(jLabel2))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 3, Short.MAX_VALUE)
                                        .addComponent(lblDireccionConfirmar)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnEditarConfirmar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                        .addComponent(btnConfirmarPedido))
                                    .addComponent(txtDireccionConfirmar)
                                    .addComponent(txtRestauranteConfirmar)
                                    .addComponent(txtPedidoConfirmar))))))
                .addGap(0, 117, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(lblPortada)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblPortada, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreConfirmar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefonoConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefonoConfirmar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccionConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDireccionConfirmar))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRestauranteConfirmar)
                    .addComponent(txtRestauranteConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtPedidoConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmarPedido)
                    .addComponent(btnEditarConfirmar))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPedidoConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPedidoConfirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPedidoConfirmarActionPerformed

    private void txtNombreConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreConfirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreConfirmarActionPerformed

    private void txtTelefonoConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoConfirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoConfirmarActionPerformed

    private void txtDireccionConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionConfirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionConfirmarActionPerformed

    private void txtRestauranteConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRestauranteConfirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRestauranteConfirmarActionPerformed

    private void btnConfirmarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarPedidoActionPerformed
        // TODO add your handling code here:
        try {
            // Recuperar datos del formulario
            String nombre = txtNombreConfirmar.getText();
            int telefono = Integer.parseInt(txtTelefonoConfirmar.getText());
            String direccion = txtDireccionConfirmar.getText();
            Cliente cliente = new Cliente(nombre, telefono, direccion);

            // Crear lista de productos desde el resumen de pedido
            ArrayList<Producto> productos = parsearProductos(txtPedidoConfirmar.getText());

            // Usar el método existente en el controlador para enviar el pedido
             Pedido elPedidoCreado = new Pedido(new Random().nextInt(100000) + 1, cliente, new Restaurante(txtRestauranteConfirmar.getText(), productos));
                controlador.enviarPedido(elPedidoCreado);


            // Mensaje de confirmación y cierre de ventana
            JOptionPane.showMessageDialog(this, "Pedido confirmado y enviado al servidor.");
            this.dispose(); // Cierra la ventana después de enviar el pedido
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, verifique los datos. El número de teléfono debe ser válido.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al procesar el pedido: " + e.getMessage());
        }
    }//GEN-LAST:event_btnConfirmarPedidoActionPerformed

    private void btnEditarConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarConfirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ValidarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ValidarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ValidarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ValidarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ValidarPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmarPedido;
    private javax.swing.JButton btnEditarConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDireccionConfirmar;
    private javax.swing.JLabel lblNombreConfirmar;
    private javax.swing.JLabel lblPortada;
    private javax.swing.JLabel lblRestauranteConfirmar;
    private javax.swing.JLabel lblTelefonoConfirmar;
    private javax.swing.JTextField txtDireccionConfirmar;
    private javax.swing.JTextField txtNombreConfirmar;
    private javax.swing.JTextField txtPedidoConfirmar;
    private javax.swing.JTextField txtRestauranteConfirmar;
    private javax.swing.JTextField txtTelefonoConfirmar;
    // End of variables declaration//GEN-END:variables
}
